/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Racecrazy;

public class App {

        public static void main(String[] args) {
            Veiculo fusca = new Veiculo(new MotordeCarrinhodeRoleman());
            Veiculo ferrari = new Veiculo(new Motordefazer());
            Veiculo lamborguini = new Veiculo(new MotorSuzuki());
            
            System.out.println(fusca.acelerar());
            System.out.println(ferrari.acelerar());
            System.out.println(lamborguini.acelerar());
            }

    Object getGreeting() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

}
